### ISSUE TITLE
Support for node v6

### ISSUE THREAD

**Issue by dhessler** [activescott/serverless-http-invoker#5]
Hello, I am testing my serverless app in a docker container emulating the aws runtime, thus running node 6.10.

I am getting the following error:
```
TypeError: URL is not a constructor
 at Function.parseQueryStringParameters (node_modules/serverless-http-invoker/index.js:125:19)
 at initializeServerless.then.then.httpEvents (node_modules/serverless-http-invoker/index.js:72:52)
```

This is happening because serverless-http-invoker is using node v8 syntax here:
```
const { URL } = require('url')
```

Would it be possible to change this or the packaging system to support node v6?
Thanks!

**Comment by activescott** [comment]
@dhessler Absolutely! If you wouldn't mind, make the change you want and submit a PR and as long as I can still run all the tests here (and I'll double check a couple local projects where I'm using this) then I'll merge your PR.
