### ISSUE TITLE
mergeResourceArrays probably should be mergeArrays

### ISSUE THREAD

**Issue by SirIle** [activescott/serverless-http-invoker#9]
It looks like serverless has changed some of the method names causing invoker to crash on line 43 when it initializes. It tries to call a function  "sls.service.mergeResourceArrays()" but it looks like there's only a method "sls.service.mergeArrays()" in the serverless implementation. Would this be the correct method to call at that stage?

**Comment by activescott** [comment]
@SirIle That is possible. If you try it out and the tests pass feel free submit a PR and I'll be happy to merge and push out a new version of the npm package.

**Comment by SirIle** [comment]
Hi, could you merge the PR if it's okay, please?

**Comment by activescott** [comment]
Thanks @SirIle! I will look at this tomorrow and try to get it merged.
